### ISSUE TITLE
API 개발 요청 리스트

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#28]
안녕하세요 규현님!
API 개발 요청할 리스트 작성해서 드립니다.
한번에 다 생각 나는 것은 아니라, 생각 나는대로 추가하겠습니다!

---

- [x] 회차 삭제 API 
- [x] 할일 목록 조회 API 수정 #30 
- [x] 자신이 참여하는 스터디 목록 조회 API (*Home 화면) #32 
- [x] Task 추가시 taskId를 반환하도록 수정 요청 #25 
- [x] Task의 수행 여부 수정 API #25
- [x] GET users 에선 nickname, GET tasks 에선 nickName 인데 어떤게 맞나요?!
- [x] GET users에서 picture이 빠져있는 것 같습니다
- [x] 할일 진행정도 계산 -> front에서 계산
- [x] 회차 상세보기시 회차 참여자들의 일관된 정렬 요청
- [x] GET /api/studies 에서 스터디 색상인 color도 함께 return 요청
- [x] 폰 모델 -> Later
- [x] 회원 가입시 프로필 메세지 필요 -> 별도로 설정 가능하도록 결정

**Comment by rbgus2002** [comment]
넵 감사합니다~!

**Comment by rbgus2002** [comment]
회차 삭제 API 개발 완료했습니다~

**Comment by Arkady1356** [comment]
Updated

**Comment by rbgus2002** [comment]
굳 아주 빠르게 작업했습니다 ㅋㅋ 일하십시오~ @Arkady1356

**Comment by Arkady1356** [comment]
UPDATED !! EMERGENCY 마지막꺼 !! 해주세요 !!

**Comment by rbgus2002** [comment]
>  GET users 에선 nickname, GET tasks 에선 nickName 인데 어떤게 맞나요?!

GET tasks에서 nickname으로 수정했습니다!

**Comment by Arkady1356** [comment]
[UPDATED]

**Comment by rbgus2002** [comment]
* 토큰 만료 기간 한달로 변경했습니다.
* GET /api/users에서 프로필 사진을 나타내는 picture 필드 추가했습니다.
* GET /api/studies에서 스터디 색상을 나타내는 color 필드 추가했습니다.

**Comment by rbgus2002** [comment]
* GET /api/studies/list에서 회차가 존재하지 않는 경우 회차 번호를 나타내는 roundSeq를 1로 response 하도록 변경했습니다.
